In [1]:
import numpy as np

ModuleNotFoundError: No module named 'yaml'

In [3]:
a = np.zeros((3,2))
print(a)
print(a.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [4]:
b = np.ones((3,2,3))
c = np.linspace(2,100,300)
c.ndim
print(b/300)

[[[0.00333333 0.00333333 0.00333333]
  [0.00333333 0.00333333 0.00333333]]

 [[0.00333333 0.00333333 0.00333333]
  [0.00333333 0.00333333 0.00333333]]

 [[0.00333333 0.00333333 0.00333333]
  [0.00333333 0.00333333 0.00333333]]]


In [5]:
d = np.random.randint(10, size = 5)
d

array([0, 8, 9, 6, 1])

In [56]:
f = np.array([1,2,3])
print(f.nbytes)
f.dtype


24


dtype('int64')

In [71]:
u = np.array([5,6,7])
i = np.array([f,u,u])
j = np.transpose(i)
print(i)
print(j)


[[1 2 3]
 [5 6 7]
 [5 6 7]]
[[1 5 5]
 [2 6 6]
 [3 7 7]]


In [96]:
print(np.vstack([i,j]))
print(np.hstack([i,j]))
print('\n')
print(np.stack([i,j],axis=0)) # stack function stacks matrices/tensors up in the new axis. Think of the multidimensional tensor representation and this will make sense
print(np.concatenate([i,j],axis=1))
# in general, there's no reason to use vstack and hstack and dstack instead of concatenate which just joins matrices or tensors together along an existing, specified dimension.

[[1 2 3]
 [5 6 7]
 [5 6 7]
 [1 5 5]
 [2 6 6]
 [3 7 7]]
[[1 2 3 1 5 5]
 [5 6 7 2 6 6]
 [5 6 7 3 7 7]]


[[[1 2 3]
  [5 6 7]
  [5 6 7]]

 [[1 5 5]
  [2 6 6]
  [3 7 7]]]
[[1 2 3 1 5 5]
 [5 6 7 2 6 6]
 [5 6 7 3 7 7]]


In [14]:
g = np.random.rand(4,5000,3000)*10
import time
start_t = time.time()
for i in range(1000000):
    g[0,1:2000,2:1000]
print(time.time()-start_t)
del g

0.3341691493988037


In [26]:
k = np.repeat(np.array([f]),5)
k

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [33]:
h = np.ones((5,5))
h[1:-1,1:-1] = np.zeros((3,3))
h[2,2] = 9
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
l = np.ones((3,4))
p = np.full((4,3),2)
w = np.matmul(l,p)
w

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [42]:
np.linalg.det(w)

0.0

In [45]:
w[0,2]=2
w[1,1]=3
np.linalg.inv(w)
np.linalg.

array([[ 1.66666667e-01,  2.00000000e-01, -2.41666667e-01],
       [ 1.11022302e-17, -2.00000000e-01,  2.00000000e-01],
       [-1.66666667e-01,  0.00000000e+00,  1.66666667e-01]])

In [47]:
t = np.random.randint(0,10,(2,3))
t

array([[5, 9, 3],
       [2, 4, 3]])

In [51]:
np.min(t,axis=0)

array([2, 4, 3])

In [50]:
np.max(t)

9

In [55]:
np.sum(t,axis=1)

array([17,  9])

In [108]:
file_data = np.genfromtxt('data.txt',delimiter=',',dtype='int32')
float_data = file_data.astype('float32')
float_data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]], dtype=float32)

In [143]:
file_data>50
file_data.shape

(3, 18)

In [145]:
# indexing by array/list
print(file_data[:,[1,4,8]])
print(file_data[:,np.array([1,4,8])])
print(file_data[[1,2,0],[2,3,4]])

[[ 13 196  34]
 [ 42 766   6]
 [ 22 999  78]]
[[ 13 196  34]
 [ 42 766   6]
 [ 22 999  78]]
[ 12  11 196]


In [123]:
# indexing by boolean (which of course requires number of booleans match the number of dimensions along that axis)
file_data[:,[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, True, False]]
file_data[file_data>50] # since we inputs a 2D array, this smartly flattens both 

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [148]:
np.all(file_data>50,axis=0) # return true for an axis only if all elements along the axis are true
np.any(file_data>30,axis=1) # return true for an axis only if any elements along the axis are true

array([ True,  True,  True])

In [154]:
print(~((file_data>50) & (file_data<100))) # all bit-wise operations are now element-wise

[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]


In [159]:
np.argmax(file_data,axis=1)

array([4, 4, 4])

In [158]:
new_data = np.where(file_data>50,100,0) # fill in 100 for True, 0 for False
new_data

array([[  0,   0,   0,   0, 100, 100,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 100, 100,   0, 100,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 100,   0,   0,   0, 100,   0,   0,   0,   0,
          0,   0,   0, 100, 100]])